name: browser
base: core24
version: "0.2"
summary: Snap that consumes proxy config.
description: |
  Snap that consumes proxy config.
grade: devel
confinement: strict

plugs:
  network-proxy-state:
    interface: confdb
    account: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN
    view: network/proxy-state

parts:
  browser:
    plugin: python
    source: .
    parse-info:
      - setup.py
    python-packages:
      - requests==2.32.5
      - html2text==2025.4.15
      - connect-markdown-renderer==3.0.0

apps:
  browser:
    command: /bin/browser-cli
    plugs:
      - network
      - network-proxy-state
