name: net-ctrl
base: core24
version: "0.2"
summary: The custodian of the network confdb.
description: |
  The custodian of the network confdb.
grade: devel
confinement: strict

plugs:
  network-proxy-admin:
    interface: confdb
    account: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN
    view: network/proxy-admin
    role: custodian

  network-proxy-state:
    interface: confdb
    account: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN
    view: network/proxy-state
    role: custodian

parts:
  net-ctrl:
    plugin: python
    source: .
    python-packages:
      - validators==0.35.0
    override-prime: |
      snapcraftctl prime
      mkdir -p ${SNAPCRAFT_PRIME}/bin
      cp ${SNAPCRAFT_PART_SRC}/bin/sh ${SNAPCRAFT_PRIME}/bin

apps:
  sh:
    command: /bin/sh
    plugs:
      - network-proxy-admin
      - home
