#!/usr/bin/env python3

import json
import subprocess

import validators


cmd = f"snapctl get --view :network-proxy-admin -d"
proc = subprocess.run(cmd.split(), capture_output=True, text=True)
if proc.returncode != 0:
    cmd = f"snapctl fail {proc.stderr}"
    subprocess.run(cmd.split())
    exit(1)

config = json.loads(proc.stdout)

for protocol, proxy_config in config.items():
    # check that the URL format is valid
    url = proxy_config.get("url")
    if url and not validators.url(url, simple_host=True):
        err = f"failed to validate url: {url}"
        cmd = f"snapctl fail {err}"
        subprocess.run(cmd.split())
        print(err)
        exit(1)

    # ensure that internal company URLs are never proxied
    internal = "*://*.company.internal"
    bypass = proxy_config.get("bypass", [])
    if internal not in bypass:
        bypass.append(internal)

        # save changes
        bypass_json = json.dumps(bypass, separators=(',', ':'))
        subprocess.run([
            "snapctl", "set", "--view", "-t", ":network-proxy-admin",
            f"{protocol}.bypass={bypass_json}"
        ])
